### ISSUE TITLE
Not restoring view state correctly

### ISSUE THREAD

**Issue by sockeqwe** [jshvarts/MosbyMVP#3]
In [GreetingViewController](https://github.com/jshvarts/MosbyMVP/blob/master/conductor-hello-world-viewstate/src/main/java/com/jshvarts/mosbymvp/GreetingViewController.kt) you should implement `onViewStateInstanceRestored(boolean instanceStateRetained)`. 

Following scenario:
Lets say a user clicks on the greeting button, then `presenter. loadGreeting()` is invoked. Presenter calls `view. showLoading()` (I think this method should contain a call like `viewState.setShowLoading()`). So your app is in LOADING state.
Let's assume that loading the greeting takes quite some time and your app is killed (process death). Since you use a `RestorableViewState` the state will be saved into `Bundle`  and restored from it afterwards.

Once the user restarts your app, ViewState will be restored (from Bundle) and ProgressBar is shown again on screen.

**BUT** you actually never invoke `presenter. loadGreeting()` again, so LOADING state will last forever.

Possible fix:
Don't use a RestoreableViewState
OR
implement onViewStateInstanceRestored() properly

```kotlin
override fun onViewStateInstanceRestored(instanceStateRetained : boolean) {
    if (!instanceStateRetained) {  // is false on process death --> state restored from bundle
        if (viewState.isLoading())
           presenter.loadGreeting() // restart loading process after process death
   }
}
```

I think in 95% of the cases it is ok to no use a `RestoreableViewState` but rather reload the entire view  on process death as it would be the first time the view is displayed. To do that just don't use a RestoreableViewState instance but rather any other ViewState (will only be kept im memory i.e. for screen orientation changes, but not persisted in bundle).

If that is not suitable for you, you should implement `onViewStateInstanceResored()` properly  to bring your presenter back in the correct state i.e. by calling `presenter.loadGreeting()`

**Comment by jshvarts** [comment]
@sockeqwe thanks for the detailed report! Will take a look soon.

**Comment by jshvarts** [comment]
@sockeqwe Can you please review https://github.com/jshvarts/MosbyMVP/pull/4 which addresses this issue?

Also, http://hannesdorfmann.com/mosby/static/javadoc/com/hannesdorfmann/mosby3/mvp/viewstate/RestorableViewState.html says "Activities can only use this kind of ViewState". Since https://github.com/jshvarts/MosbyMVP/blob/master/hello-world-viewstate/src/main/java/com/jshvarts/mosbymvp/GreetingViewState.kt is using Activity as View rather than Conductor Controller, I left its view state as type `RestorableViewState`. Is this a good approach or should I change it to be of type `ViewState` too? And if so, is the Javadoc for `RestorableViewState` valid?

**Comment by sockeqwe** [comment]
Oops, docs are outdated (they are referring to Mosby 2.x). This changed in Mosby 3.0, Basically, (in memory) ViewState can be used for Activity, Fragment and ViewGroups. RestoreableViewState of course can be also used for all of them but would be restored on process death.

**Comment by jshvarts** [comment]
Merged the fix. Thanks!
